Vagrant.configure(2) do |config|
  #Configure box
  config.vm.box = "generic/centos9s"
  config.vm.box_url = "https://app.vagrantup.com/generic/boxes/centos9s/versions/4.0.4/providers/libvirt.box"
  config.vm.provision "shell", inline: "systemctl disable --now firewalld"

  #Configure Server
  config.vm.define "hpottierS" do |control|
    control.vm.hostname = "hpottierS"
    control.vm.network "private_network", ip: "192.168.42.110"
    control.vm.provider "libvirt" do |v|
      v.memory = 512
      v.cpus = 1
    # control.vm.provider "virtualbox" do |v|
    #   v.customize ["modifyvm", :id, "--name", "hpottierS"]
    #   v.memory = 512
    #   v.cpus = 1
    end

    # Execute shell commands to configure server
    config.vm.provision "shell", privileged: true, inline: "curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644"
  end

  #Configure Worker
  config.vm.define "hpottierSW" do |control|
    control.vm.hostname = "hpottierSW"
    control.vm.network "private_network", ip: "192.168.42.111"
    control.vm.provider "libvirt" do |v|
      v.memory = 512
      v.cpus = 1
    # control.vm.provider "virtualbox" do |v|
    #   v.customize ["modifyvm", :id, "--name", "hpottierSW"]
    #   v.memory = 512
    #   v.cpus = 1
    end

    # Execute shell commands to configure worker
    config.vm.provision "shell", privileged: true, inline: "curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644"
  end

end
