# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Vagrantfile                                        :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hpottier <hpottier@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/07/20 17:10:29 by hpottier          #+#    #+#              #
#    Updated: 2022/07/21 16:31:03 by hpottier         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

Vagrant.configure(2) do |config|
	config.vm.box = "generic/centos8s"
	config.vm.box_url = "https://app.vagrantup.com/generic/boxes/centos8s/versions/4.1.0/providers/virtualbox.box"
	config.vm.synced_folder ".", "/vagrant"
	config.vm.provision "shell", privileged: true, inline: "systemctl disable firewalld --now"

	config.vm.define "part3vm" do |control|
		control.vm.hostname = "part3vm"
		control.vm.network "private_network", ip: "192.168.42.110"
		control.vm.provider "virtualbox" do |v|
			v.customize ["modifyvm", :id, "--name", "part3vm"]
			v.memory = 8192
			v.cpus = 2
		end
		control.vm.provision "shell", inline: <<~SHELL
			sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
			sudo yum makecache
			sudo yum install -y docker-ce docker-ce-cli containerd.io
			sudo systemctl enable --now docker
			/vagrant/kubectlInstall.sh
			sudo yum install -y kubectl
			/vagrant/k3dinstall.sh
			SHELL
	end
end
